### ISSUE TITLE
have a new version of WStore, WMarket, Repository RI configuration guide?

### ISSUE THREAD

**Issue by ftfniqpl** [conwetlab/wstore#11]
I downloaded the latest version from github WStore, WMarket, Repository RI source installation,
 refer to the document [https://forge.fiware.org/plugins/mediawiki/wiki/fiware/index.php/Business_Framework_(Package)_-_Installation_Guide](https://forge.fiware.org/plugins/mediawiki/wiki/fiware/index.php/Business_Framework_%28Package%29_-_Installation_Guide) .

The problem is that WStore management interface, I can not add marketplace information, 
"3. Check that the Marketplace is configured" refer to the above document that this section, 
how do I configure the marketplace? 
For the latest version of Business_Framework configuration documentation? 

Thank you.

**Comment by fdelavega** [comment]
Hi,

This business framework documentation refers to a package that was offered as a single system, and does not explain the integration configuration of the current GEs version. This documentation can be found in readthedocs:

http://wstore.readthedocs.io/en/latest/
http://wmarket.readthedocs.io/en/latest/
http://repository-ri.readthedocs.io/en/latest/

Nevertheless, this FIWARE business framework composed of different GEs has been deprecated and is in support mode. All these components will be replaced by a single system that will be released by the end of the summer.

**Comment by ftfniqpl** [comment]
OK, Thanks.
