### ISSUE TITLE
Ubuntu 14.04 installation

### ISSUE THREAD

**Issue by abusquets** [conwetlab/wstore#6]
I try to install into Ubuntu 14.04 and I have this error

 line 34, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/home/administrador/wstore/src/virtenv/local/lib/python2.7/site-packages/django/db/utils.py", line 92, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/home/administrador/wstore/src/virtenv/local/lib/python2.7/site-packages/django/db/utils.py", line 44, in load_backend
    raise ImproperlyConfigured(error_msg)
django.core.exceptions.ImproperlyConfigured: 'django_mongodb_engine' isn't an available database backend.
Try using django.db.backends.XXX, where XXX is one of:
    'dummy', 'mysql', 'oracle', 'postgresql_psycopg2', 'sqlite3'

**Comment by fdelavega** [comment]
The problem is that the version 3 of pymongo is not completely compatible with the version django non-rel. This issue can be fixed forcing the version of pymongo to 2.8

**Comment by abusquets** [comment]
Thanks, now is ok.
