### ISSUE TITLE
Where Can i find Resposity URL?

### ISSUE THREAD

**Issue by alex8224** [conwetlab/wstore#8]
Hi
  I started WStore in docker follow install guide instruction, But I havent any Resposity URL 
  Could any one tell me Where can i find Resposity url?
 Tks a lot

**Comment by fdelavega** [comment]
Hi,
The repository is not anymore mandatory for running WStore. Nevertheless, if you want to use want we are also proving a Docker image at: https://hub.docker.com/r/fiware/repository-ri/

Additionally, the source code is at: https://github.com/conwetlab/Repository-RI
Best,
Francisco

**Comment by alex8224** [comment]
Ok, thanks . I got it.


Francisco de la Vega <notifications@github.com>于2015年10月29日周四 下午6:18写道：
